---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-parca
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonKustomize: parca
                addonKustomizeNamespace: parca-system
                addonKustomizeVersion: v0.25.0
              selector:
                matchExpressions:
                  - key: enable_parca
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: dev
              values:
                addonKustomize: parca
                addonKustomizeNamespace: parca
                addonKustomizeVersion: v0.25.0
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values:
                addonKustomize: parca
                addonKustomizeNamespace: parca
                addonKustomizeVersion: v0.25.0
  template:
    metadata:
      name: addon-{{name}}-{{values.addonKustomize}}
    spec:
      project: addons
      source:
          repoURL: '{{metadata.annotations.addons_repo_url}}'
          path: 'kustomize/{{values.addonKustomize}}/{{values.addonKustomizeVersion}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
      destination:
        namespace: '{{values.addonKustomizeNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
